### ISSUE TITLE
This library no longer works on python 2.7

### ISSUE THREAD

**Issue by jondkelley** [dyninc/dyn-python#129]
dyn==1.8.1 with python 2.7 

```from dyn.tm.session import DynectSession
from dyn.tm.zones import *
from dyn.tm.errors import DynectAuthError

   print(DynectSession(
       'organization', 'user','xxxxx'))
```

Will raise dyn.tm.errors.DynectAuthError

Traceback (most recent call last):
 File "libdynect.py", line 379, in <module>
   'organization', 'user','xxxxx'))
 File "/usr/local/lib/python2.7/site-packages/dyn/core.py", line 51, in __call__
   cur_thread: super(_Singleton, cls).__call__(*args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/dyn/tm/session.py", line 57, in __init__
   self.authenticate()
 File "/usr/local/lib/python2.7/site-packages/dyn/tm/session.py", line 178, in authenticate
   raise DynectAuthError('Unable to access the API host')
dyn.tm.errors.DynectAuthError: Unable to access the API host

**Comment by jondkelley** [comment]
This happens when the requests.get() fails generally

        try:
            response = self.execute('/Session/', 'POST', api_args)
        except IOError:
            raise DynectAuthError('Unable to access the API host')
