### ISSUE TITLE
Latest version has Syntax Error in core.py on Python 2.6

### ISSUE THREAD

**Issue by chaimpeck** [dyninc/dyn-python#48]
When I import from  `dyn.tm.session`, I get a syntax error:

    Traceback (most recent call last):
      File "dyn-python-test.py", line 1, in <module>
        from dyn.tm.session import DynectSession
      File "/usr/local/lib/python2.6/site-packages/dyn/tm/session.py", line 8, in <module>
        from ..core import SessionEngine
      File "/usr/local/lib/python2.6/site-packages/dyn/core.py", line 23
        return {x: dict_obj[x] for x in dict_obj if dict_obj[x] is not None and
                                 ^
    SyntaxError: invalid syntax

I am using Python 2.6.5:

    $ python --version
    Python 2.6.5

and `dyn-python-1.1.0`

It looks like dict comprehension is a Python 2.7 feature:
https://www.python.org/dev/peps/pep-0274/

However, the documentation says:
"Requires Python 2.6 or higher, or the "simplejson" package."

I suspect that a simple fix would be to change that line to this:

    return dict((x, dict_obj[x]) for x in dict_obj if dict_obj[x] is not None and
            not hasattr(dict_obj[x], '__call__'))

However, after doing that it looks like there are other places that are also not Python 2.6 compatible.

So, it might be best to just update the docs to let everyone know that it is not compatible with Python 2.6.

**Comment by chaimpeck** [comment]
This is also a problem with previous versions. I am getting this error in all releases, going back to 1.0.1, using Python 2.6:

    Traceback (most recent call last):
      File "/usr/local/lib/python2.6/site-packages/dyn/__init__.py", line 16, in <module>
        __title__      = '{} version {}'.format(__name__, __version__)

Using format strings without indexes (i.e. `'{0} version {1}'`) was introduced in Python 2.7.

**Comment by derekargueta** [comment]
@Northover unless there's intended support for Python 2.6, this issue appears closable.
